config/routes.rb
Rails.application.routes.draw do
  root "categories#index"
  get 'search', to: 'products#search'
  resources :categories
  resources :products
  resources :users
  # get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  # resources :categories do
  #   resources :products
  # end
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contacts'
  get 'static_pages/help'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :categories, dependent: :destroy
    validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :name, presence: true
  has_attached_file :image, styles: { large: "1280x720>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
    validates :nikname, presence: true, length: { maximum: 50 }
    has_secure_password
    validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
    def index
      @categories = Category.all
    end
 
    def show
      @category = Category.find(params[:id])
    end
  
    def new
      @category = Category.new
    end
  
    def create
      @category = Category.new(category_params)
  
      if @category.save
        redirect_to @category
      else
        render :new
      end
    end
  
    def edit
      @category = Category.find(params[:id])
    end
  
    def update
      @category = Category.find(params[:id])
  
      if @category.update(category_params)
        redirect_to @category
      else
        render :edit
      end
    end
  
    def destroy
      @category = Category.find(params[:id])
      @category.destroy
  
      redirect_to root_path
    end
  
    private
    def category_params
      params.require(:category).permit(:name, :image)
    end
  
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def search
    @products = Product.where("name LIKE ?", "%" + params[:q] + "%")
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(nikname: params[:session][:nikname])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contacts
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      @users = User.all
    end
    
    def show
      @user = User.find(params[:id])
    end
      
    def new
      @user = User.new
    end
      
    def create
      @user = User.new(user_params)
        if @user.save
          log_in @user
          flash[:success] = 'Welcome to best site EnduroIsHard'
          redirect_to @user
        else
          render 'new'
        end
    end
      
    def edit
      @user = User.find(params[:id])
    end
      
    def update
      @user = User.find(params[:id])
        if @user.update(user_params)
          flash[:success] = "Profile updated"
          redirect_to @user
        else
          render 'edit'
        end
    end
    
    private
  
    def user_params
      params.require(:user).permit(:nikname, :password,
                                    :password_confirmation)
    end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
        # Возвращает полный заголовок на основе заголовка страницы.
        def full_title(page_title = '')
            base_title = "GlobusSearch"
            if page_title.empty?
                base_title
            else
                "#{page_title} | #{base_title}"
            end
        end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
      # Возвращает текущего вошедшего пользователя (если есть).
      def current_user
        @current_user ||= User.find_by(id: session[:user_id])
      end
    
      # Возвращает true, если пользователь зарегистрирован, иначе возвращает false.
      def logged_in?
        !current_user.nil?
      end
    
      def log_out
        session.delete(:user_id)
        @current_user = nil
      end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, html: { multipart: true } do |form| %>
<%
=begin%>
 <div><%= image_tag @category.image.url(:large) %></div> 
<%
=end%>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @category.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  <%
=begin%>
 </div>
 <%= form.file_field :image %>
  <div> 
<%
=end%>
      <%=form.submit %>
  </div>
  <%= link_to "В главное меню", root_path, class:"btn btn-lg btn-primary" %>
<% end %>

app/views/categories/edit.html.erb
<h1>Редактирование категории</h1>
<div class="container-fluid">
<%= render "form", category: @category %>

app/views/categories/index.html.erb
<h1>Категории товаров</h1>

<ul class="list-inline">
  <% @categories.each do |form| %>
    <li>
      <%= link_to form.name, form %>
    </li>
  <% end %>
</ul>

<%= link_to "Добавить категорию товара", new_category_path, class:"btn btn-lg btn-primary" %>

app/views/categories/new.html.erb
<h1>New Article</h1>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<% provide(:title, "Просмотр категорий") %>
<h1><%= @category.name %></h1>
<%= link_to "Добавить товар", new_product_path, class:"btn btn-lg btn-primary" %>
<%
=begin%>
 <div><%= image_tag  @category.image.url(:large), {:class => 'img-fluid img-thumbnail'}%></div> 
<%
=end%>
<ul class="list-inline">
  <li class="list-group-item"><%= link_to "Редактировать категорию товара", edit_category_path(@category) %></li>
  <li class="list-group-item"><%= link_to "Удалить категорию товара", category_path(@category),
                  method: :delete,
                  data: { confirm: "Вы уверены?" } %></li>
  <li class="list-group-item"><%= link_to "Назад", root_path %></li>
</ul>

app/views/layouts/_footer.html.erb
  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2021  NIKTEXNIK</p>
  </footer>

app/views/layouts/_header.html.erb
<%
=begin%>
 <header class="navbar navbar-fixed-top navbar-inverse">
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home", '#'%></li>
                <li><%= link_to "Help", '#' %></li>
                <li><%= link_to "Users", '#' %></li>
                <li><%= link_to "Profile", '#' %></li>
                <li><%= link_to "Settings", '#' %></li>
            </ul>
        </nav>
</header> 
<%
=end%>
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">GlobusTverSearch</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= link_to "Админ???", login_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Помощь", static_pages_help_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Контакты", static_pages_contacts_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "О нас", static_pages_about_path, class:"nav-link"%>
        </li>
      </ul>
      <form class="d-flex" action="/search">
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Поиск товара</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<%= render 'layouts/header' %>
  <body>
   <div class="container">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
    </div>
<main class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <%= yield %>
</main>
   
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/products/_form.html.erb
<%= form_for @product, html: { multipart: true } do |form| %>
<div><%= image_tag @product.image.url(:large) %></div>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @product.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
 <%= form.file_field :image %>
  <div>
<%
=begin%>
 <%= form.select :category_id, [1,2,3,4,5,6], selected: '1' %> 
<%
=end%>
      <%=form.submit %>
  </div>
  <%= link_to "В главное меню", root_path, class:"btn btn-lg btn-primary" %>
<% end %>

app/views/products/edit.html.erb
<h1>Редактирование категории</h1>
<div class="container-fluid">
<%= render "form", product: @product %>

app/views/products/index.html.erb
<h1>Категории товаров</h1>

<ul class="list-inline">
  <% @products.each do |form| %>
    <li class="list-group-item">
      <%= link_to form.name, form %>
    </li>
  <% end %>
</ul>
<%= link_to "Добавить товар", new_product_path, class:"btn btn-lg btn-primary" %>

app/views/products/new.html.erb
<h1>New Article</h1>

<%= render "form", product: @product %>

app/views/products/search.html.erb
<h1>search</h1>

 <%= render @products %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

 <div><%= image_tag  @product.image.url(:large), {:class => 'img-fluid img-thumbnail'}%></div> 

<ul class="list-inline">
  <li class="list-group-item"><%= link_to "Редактировать категорию товара", edit_product_path(@product) %></li>
  <li class="list-group-item"><%= link_to "Удалить категорию товара", product_path(@product),
                  method: :delete,
                  data: { confirm: "Вы уверены?" } %></li>
  <li class="list-group-item"><%= link_to "Назад", root_path %></li>
</ul>

<%= render "products/new" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
The form contains <%= pluralize(@user.errors.count, "error") %>.
</div>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
Это приложение поможет тебе найти необходимый товар на карте гипермаркета Глобус Тверь!

app/views/static_pages/contacts.html.erb
<% provide(:title, 'Contact') %>
<h1>Контакты</h1>
<p>По вопросам и пожеланиям писать на email niktiek@yandex.ru</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
niktiek@yandex.ru

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
  <main class="px-3">
  <h1>Добро пожаловать в приложение "Поиск товаров Глобус Тверь"</h1>
    <p class="lead"> Если вы админ, то залогиньтесь</p>
  </main>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
        <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <%= f.submit "Save changes", class: "btn btn-primary" %>
        <% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<ul class="users">
<% @users.each do |user| %>
<li>
<%= link_to user.nikname, user %>
</li>
<% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>
<%= f.label :nikname %>
<%= f.text_field :nikname, class: 'form-control' %>
<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>
<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>
<%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.nikname) %>
<h1><%= @user.nikname %></h1>
<div>
Теперь вы можете редактировать категории товаров и добавлять товар!
</div>
<div>   
<li> <%= link_to "Редактировать товар и категории", root_path%></li> </div>
<li> <%= link_to "Больше не хочу быть админом((((", logout_path, method: "delete" %></li> </div>